service: wheel-of-missfortune

provider:
  name: aws
  runtime: nodejs6.10
  stage: dev
  region: ap-southeast-2

  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "dynamodb:*"
      Resource:
        - "arn:aws:dynamodb:*"

plugins:
  - serverless-plugin-inject-dependencies
  - serverless-plugin-bespoken

functions:
  slackInput:
    handler: slackInput.handleInput
    environment:
      RASPBERRY_ENDPOINT: ${env:RASPBERRY_ENDPOINT}
      SLACK_ENDPOINT: ${env:SLACK_ENDPOINT}
    events:
      - http:
          path: spin
          method: post
  result:
    handler: result.colormapping
    environment:
      SLACK_ENDPOINT: ${env:SLACK_ENDPOINT}
    events:
      - http:
          path: color/{hexa}/{wheelId}
          method: get

package:
  individually: true
  exclude:
    - tmp/**
    - .git/**
